.PHONY: clean All

All:
	@echo "----------Building project:[ lab4 -  ]----------"
	@cd "lab4" && "$(MAKE)" -f  "lab4.mk"
clean:
	@echo "----------Cleaning project:[ lab4 -  ]----------"
	@cd "lab4" && "$(MAKE)" -f  "lab4.mk" clean
